site_name: Diseño de experiencias de aprendizaje con IA para el análisis, la automatización y la 
           toma de decisiones
nav: 
  - Introducción: intro.md
  - Diseño del curso: design.md
  - Trayecto de actividades: trayecto.md
  - Recursos: recursos.md
  - Planes de estudio: planes.md
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Cambiarse al modo claro
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Cambiarse al modo oscuro
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

